-- MySQL Script generated by MySQL Workbench
-- Mon Sep 25 12:40:19 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_bimestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_bimestre` (
  `id` BIGINT NULL AUTO_INCREMENT,
  `tipoEducacaoBasica` VARCHAR(255) NOT NULL,
  `bimestre` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_materias` (
  `id` BIGINT NULL AUTO_INCREMENT,
  `linguaPortuguesa` DECIMAL NOT NULL,
  `matematica` DECIMAL NOT NULL,
  `biologia` DECIMAL NOT NULL,
  `fisica` DECIMAL NOT NULL,
  `quimica` DECIMAL NOT NULL,
  `artes` DECIMAL NOT NULL,
  `educacaoFisica` DECIMAL NOT NULL,
  `ingles` DECIMAL NOT NULL,
  `filosofia` DECIMAL NOT NULL,
  `geografia` DECIMAL NOT NULL,
  `historia` DECIMAL NOT NULL,
  `sociologia` DECIMAL NOT NULL,
  `ciencias` DECIMAL NOT NULL,
  `tb_bimestre_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_materias_tb_bimestre_idx` (`tb_bimestre_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_materias_tb_bimestre`
    FOREIGN KEY (`tb_bimestre_id`)
    REFERENCES `mydb`.`tb_bimestre` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_alunos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_alunos` (
  `id` BIGINT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `ra` VARCHAR(255) NOT NULL,
  `cpf` BIGINT NOT NULL,
  `foto` VARCHAR(255) NULL,
  `media` DECIMAL NOT NULL,
  `tb_materias_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_alunos_tb_materias1_idx` (`tb_materias_id` ASC) VISIBLE,
  UNIQUE INDEX `ra_UNIQUE` (`ra` ASC) VISIBLE,
  CONSTRAINT `fk_tb_alunos_tb_materias1`
    FOREIGN KEY (`tb_materias_id`)
    REFERENCES `mydb`.`tb_materias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tb_usuarios` (
  `id` BIGINT NULL AUTO_INCREMENT,
  `user` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `tb_alunos_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_usuarios_tb_alunos1_idx` (`tb_alunos_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_usuarios_tb_alunos1`
    FOREIGN KEY (`tb_alunos_id`)
    REFERENCES `mydb`.`tb_alunos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
